version: 2.1

jobs:
  build:
    machine: 
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    environment:
      NAME: rg.fr-par.scw.cloud/moodwork/base-image
      BASE_IMAGE: ubuntu:20.04
      PLATFORM: amd64
      QEMU_ARCH: amd64 
      TAG_ARCH: amd64
    steps:
      - checkout
      - run: 
          name: Authenticate on Image Registry
          command: |
            docker login rg.fr-par.scw.cloud/moodwork -u nologin -p $SCW_CONTAINER_REGISTRY
      - run: 
          name: "Build moodwork docker image"
          command: |
            VERSION=$CIRCLE_TAG make build
      - run:
          name: Push to store
          command: |
            docker push $NAME:$CIRCLE_TAG-$TAG_ARCH

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker
          filters:
            branches:
              ignore: /.*/            
            tags:
              only: /.*\..*\..*/

