version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

jobs:
  build:
    machine: 
      image: ubuntu-2204:2024.04.4
      docker_layer_caching: true
    environment:
      NAME: rg.fr-par.scw.cloud/moodwork-docker-images/base-image
      AWS_IMAGE_NAME: moodwork-base-image
      BASE_IMAGE: ubuntu:24.04
      PLATFORM: amd64
      QEMU_ARCH: amd64 
      TAG_ARCH: amd64
    steps:
      - checkout
      - run: 
          name: "Print environment variables"
          command: |
            env
      - aws-cli/setup:
          profile_name: default
      - aws-ecr/ecr_login:
          region: ${AWS_DEFAULT_REGION}
      - run: 
          name: Authenticate on Image Registry
          command: |
            docker login rg.fr-par.scw.cloud/moodwork-docker-images -u nologin -p $SCW_CONTAINER_REGISTRY
      - run: 
          name: "Build moodwork docker image"
          command: |
            VERSION=${CIRCLE_BRANCH} make build
            VERSION=${CIRCLE_BRANCH} make tag_latest
      - run:
          name: Push to Scaleway store
          command: |
            docker push $NAME:latest-${TAG_ARCH}
      - run: 
          name: "Push moodwork docker image to AWS"
          command: |
            docker tag $NAME:latest-${TAG_ARCH} ${REPOSITORY_BASE}/${AWS_IMAGE_NAME}:latest-${TAG_ARCH}
            docker push ${REPOSITORY_BASE}/${AWS_IMAGE_NAME}:latest-${TAG_ARCH}

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: 
            - docker               
            - aws-ecr
  build:
    jobs:
      - build:
          context: 
            - docker
            - aws-ecr
          filters:
            branches:
              only:
                - master
                - aws

