version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

jobs:
  build:
    machine: 
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    environment:
      NAME: rg.fr-par.scw.cloud/moodwork-docker-images/base-image
      BASE_IMAGE: ubuntu:20.04
      PLATFORM: amd64
      QEMU_ARCH: amd64 
      TAG_ARCH: amd64
    steps:
      - checkout
      - aws-ecr/ecr-login:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          aws-region: ${AWS_DEFAULT_REGION}
          account-id: ${AWS_ACCOUNT_ID}
      - run: 
          name: Authenticate on Image Registry
          command: |
            docker login rg.fr-par.scw.cloud/moodwork-docker-images -u nologin -p $SCW_CONTAINER_REGISTRY
      - run: 
          name: "Build moodwork docker image"
          command: |
            VERSION=${CIRCLE_BRANCH} make build
            VERSION=${CIRCLE_BRANCH} make tag_latest
      - run:
          name: Push to store
          command: |
            docker push $NAME:latest-${TAG_ARCH}

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: 
            - docker               
            - aws-ecr
  build:
    jobs:
      - build:
          context: 
            - docker
            - aws-ecr
          filters:
            branches:
              only:
                - master
                - aws

