# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build image
        run: BASE_IMAGE=ubuntu:20.04 VERSION=latest NAME=rg.fr-par.scw.cloud/moodwork/base-image PLATFORM=amd64 QEMU_ARCH=amd64 TAG_ARCH=amd64 make build
      - name: Push image
        run: docker push rg.fr-par.scw.cloud/moodwork/base-image:latest-amd64
      - name: Cleanup image
        run: docker rmi rg.fr-par.scw.cloud/moodwork/base-image:latest-amd64